version: "3.9"
services:

    web:
        image: nginx:stable
        restart: always
        ports:
            - 8080:80
        environment:
            - DJANGO_HOST=app
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - ./www:/www
        networks:
            - backend

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8000:8000

        command: python manage.py runserver 0.0.0.0:8000
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_HOST: ${DB_HOST}
        volumes:
            - .:/app
            - ./www:/www
        networks:
            - backend

networks:
    backend:
